### ISSUE TITLE
psbook Stream vs file discrepancy

### ISSUE THREAD

**Issue by za3k** [rrthomas/psutils#25]
This is tested on 1.93

With files everything is great:
```
~/test-print $ psjoin {01..16}.ps >combined-1.ps
~/test-print $ psbook -s16 <combined-1.ps >combined-2.ps
[1] [2] [3] [4] [5] [6] [7] [8] [9] [10] [11] [12] [13] [14] [15] [16] Wrote 16 pages
```

With streams, not so much:
```
~/test-print $ psjoin {01..16}.ps | psbook -s16 >combined-2.ps
pstops: page range 16 is invalid
```

Let me know if you need anything more to reproduce

**Comment by rrthomas** [comment]
Both examples you give are using streams. However, I can repro (leaving out the `<` in the `psbook` command), and it does appear to be to do with using streams!

**Comment by bwhissel** [comment]
I also had trouble using the psutils in a filter chain. To create a folded booklet from double-sided 2-up pages, my chain looks like:
```
dvips -f book | psbook | psnup -2 > out.ps`
```

I think I tracked down the problem to the `seekable()` function in PSUtils.pm. Once STDIN has been copied to the temporary file, the `$fp` handle is closed. In a filter chain, this would be closing STDIN, and the tempfile's file handle is returned in its place.

The problem is that in the calling function `setup_input_and_output()`,  we have `$infile = seekable($infile)`. This replaces the _reference_ to STDIN with the new filehandle, but the file descriptor associated with STDIN has been closed. Since the next process `psselect` is exec'd and STDIN has been closed, the next process has no open STDIN descriptor.

One way to fix this is to reopen STDIN using the new file descriptor, so in `seekable()`, replace
```
  close $fp;
  return $ft if seek $ft, 0, SEEK_SET;
```
with something like
```
  open($fp, "<&=", fileno($ft));
  return $fp if seek $fp, 0, SEEK_SET;
```
This would replace STDIN itself with the open file descriptor pointing to the tempfile.
