### ISSUE TITLE
psbook: Explanation of “signature” and printing unclear

### ISSUE THREAD

**Issue by htgoebel** [rrthomas/psutils#43]
I try to understand how the “signature” is meant to be used and how to print the book afterwards.
May I ask you to explain. Many thanks.

With `-s 4` first eight pages are ordered 4-1-2-3-8-5-6-7.
When printing this 4 pages on a sheet side (`psnup -4`), this gives:

     Front:  4 1   Back:  8 5
             2 3          6 7

Now when binding and folding, then turning around from page 1 one will get to page 8.
Even if pages 2, 3, 6, 7 are rotated 180°and folding differently, from page 1 one will get to page 3.

When using `psnup -2` it's basically the same.

**Comment by rrthomas** [comment]
Thanks for this question. I did some research, and I see that the term "signature" does not quite mean the same thing in PSUtils as it does in traditional book-binding. In traditional book-binding, as far as I can tell, it usually refers to a single sheet of paper on which a multiple of 4 pages is printed; the sheet is then folded and cut to produce part of the book.

In PSUtils, on the other hand, a signature refers to what is often otherwise called a "section", namely a group of sheets to be folded in half. Each sheet is always printed duplex and 2-up.

The man page for `psbook` currently has this paragraph:

> psbook uses pstops to rearrange pages from a PostScript document into ‘signatures’ for printing books or booklets, creating a new PostScript file.  The signature size is the number of sides which will be folded and bound together; the number given should be a multiple of four.  Extra blank sides will be added if the file does not contain a multiple of four pages.

I suggest the following rewritten version (the first and last sentences remain the same):

> psbook uses pstops to rearrange pages from a PostScript document into ‘signatures’ for printing books or booklets, creating a new PostScript file. A ‘signature’, often called a ‘section’ in bookbinding, is a series of sheets that are folded together to be stitched into the book's binding. Each sheet has two pages per side; the number of pages in a signature must therefore be a multiple of four. Extra blank sides will be added if the file does not contain a multiple of four pages.

`psbook` only rearranges the pages; it does not impress them 2-up. The output of `psbook` should be passed to `psnup -2`.

What you do after that depends on how you will print. For example, I pass the output of `psnup -2` to `pstops '2:0(0,0),1U(1w,1h)' to rotate the pages, for printing duplex with long-edge binding (this tends to be the printer default). Alternatively, one could use the output of `psnup -2` directly with short-edge binding duplex.

I guess it would be helpful if the man page for `psbook` included some remarks about this?

Historical note: I have done a lot of work on PSUtils over many years to make the code simpler more maintainable, and to fix bugs. However, up to now I have not significantly changed the command-line interface except to fix bugs. I am planning a major new version that will drop backwards compatibility and give the opportunity to simplify the command-line interface for common use cases. This is obviously one such case! I myself have used PSUtils to produce hand-made books for over 10 years, and I had to painstakingly work out how to use it, and have encoded that learning in custom-written bash scripts. I agree that it should be possible for many uses to have much simpler and more direct uses.

The other thing that I think could be clarified is the meaning of the special signature size 1, which means "do not rearrange the pages".
