### ISSUE TITLE
tag mismatch

### ISSUE THREAD

**Issue by chenrui333** [rrthomas/psutils#51]
👋 looks like pypi has 3.0.2 and 3.0.3, while they are missed in the github repo.

<img width="466" alt="image" src="https://github.com/rrthomas/psutils/assets/1580956/5ecea77a-f2b7-47f6-896e-7d9ac2cd7edd">

**Comment by rrthomas** [comment]
Thanks for noticing this, I was on a train when I made the releases, and was having connectivity problems, so I think the PyPI bit succeeded but not the GitHub bit.

I've pushed both tags, and only made the 3.0.3 release properly, rather than go back and re-create 3.0.2.

**Comment by chenrui333** [comment]
oh, i see. :) you should use github actions to automate these releases

**Comment by rrthomas** [comment]
That could have much the same problem that one step could succeed and others fail, but I would happily take a PR to add a GitHub action. I think I would rather retain non-GitHub functionality as the actual code that is run (like the current `Makefile`) because I don't want to have to rewrite it when GitHub goes away (I have already had enough of migrating CI from Travis to AppVeyor to GitHub, and I don't want to get into that loop with releases too—my current investment in releasing on GitHub is just a single command in `Makefile`, and it does not affect the PyPI release).
